version: '3'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Ae8eayahgee9yoh8daeJ
  # dump:
  #   image: postgres:14
  #   command: bash
  #   volumes:
  #     - ./tmp:/tmp/host
  #   depends_on:
  #     - db
  web:
    build: .
    command: bundle exec rails s -b 0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=Ae8eayahgee9yoh8daeJ
    depends_on:
      - db
    links:
      - db
